import type { IconSvgElement } from "@hugeicons/react";
import {
  Activity01Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  AudioWaveformIcon,
  BotIcon,
  BrainIcon,
  Briefcase01Icon,
  Building01Icon,
  Calendar01Icon,
  CallIcon,
  CheckIcon,
  CircleIcon,
  Clock01Icon,
  CodeIcon,
  Copy01Icon,
  CpuIcon,
  CreditCardIcon,
  Database01Icon,
  Download01Icon,
  Edit01Icon,
  EyeIcon,
  FileTextIcon,
  FilterIcon,
  GlobeIcon,
  HeadphonesIcon,
  HistoryIcon,
  Home01Icon,
  InboxIcon,
  InfoIcon,
  Key01Icon,
  Layers01Icon,
  Link02Icon,
  ListIcon,
  Loading02Icon,
  LockIcon,
  Mail01Icon,
  Megaphone01Icon,
  Menu01Icon,
  MessageCircleIcon,
  MessageSquareIcon,
  Mic01Icon,
  MicOff01Icon,
  PhoneCallIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneOutgoingIcon,
  PlayIcon,
  PlusIcon,
  RadioIcon,
  RefreshCwIcon,
  Rocket01Icon,
  SaveIcon,
  Search01Icon,
  SendIcon,
  ServerIcon,
  Settings01Icon,
  ShieldCheckIcon,
  SparklesIcon,
  StarIcon,
  Tag01Icon,
  TrashIcon,
  TruckIcon,
  Upload01Icon,
  UserIcon,
  UsersIcon,
  Video01Icon,
  Wallet01Icon,
  WorkflowIcon,
  Wrench01Icon,
  XIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";

/**
 * Runtime lookup from legacy lucide icon names (as sent by the backend in
 * node/tool specs) to HugeIcons data. Unknown names fall back to CircleIcon —
 * same behaviour as the old lucide namespace lookup.
 */
const BY_LUCIDE_NAME: Record<string, IconSvgElement> = {
  Activity: Activity01Icon,
  AlertCircle: AlertCircleIcon,
  ArrowDown: ArrowDown01Icon,
  ArrowLeft: ArrowLeft01Icon,
  ArrowRight: ArrowRight01Icon,
  ArrowUp: ArrowUp01Icon,
  ArrowUpRight: ArrowUpRight01Icon,
  AudioWaveform: AudioWaveformIcon,
  Bot: BotIcon,
  Brain: BrainIcon,
  BrainCircuit: BrainIcon,
  Briefcase: Briefcase01Icon,
  Building: Building01Icon,
  Calendar: Calendar01Icon,
  Call: CallIcon,
  Check: CheckIcon,
  Circle: CircleIcon,
  Clock: Clock01Icon,
  Code: CodeIcon,
  Copy: Copy01Icon,
  Cpu: CpuIcon,
  CreditCard: CreditCardIcon,
  Database: Database01Icon,
  Download: Download01Icon,
  Edit: Edit01Icon,
  Eye: EyeIcon,
  FileText: FileTextIcon,
  Filter: FilterIcon,
  Globe: GlobeIcon,
  Headphones: HeadphonesIcon,
  History: HistoryIcon,
  Home: Home01Icon,
  Inbox: InboxIcon,
  Info: InfoIcon,
  Key: Key01Icon,
  Layers: Layers01Icon,
  Link: Link02Icon,
  List: ListIcon,
  Loader: Loading02Icon,
  Loader2: Loading02Icon,
  Lock: LockIcon,
  Mail: Mail01Icon,
  Megaphone: Megaphone01Icon,
  Menu: Menu01Icon,
  MessageCircle: MessageCircleIcon,
  MessageSquare: MessageSquareIcon,
  Mic: Mic01Icon,
  MicOff: MicOff01Icon,
  Phone: PhoneIcon,
  PhoneCall: PhoneCallIcon,
  PhoneIncoming: PhoneIncomingIcon,
  PhoneOutgoing: PhoneOutgoingIcon,
  Play: PlayIcon,
  Plus: PlusIcon,
  Radio: RadioIcon,
  RefreshCw: RefreshCwIcon,
  Rocket: Rocket01Icon,
  Save: SaveIcon,
  Search: Search01Icon,
  Send: SendIcon,
  Server: ServerIcon,
  Settings: Settings01Icon,
  ShieldCheck: ShieldCheckIcon,
  Sparkles: SparklesIcon,
  Star: StarIcon,
  Tag: Tag01Icon,
  Trash: TrashIcon,
  Truck: TruckIcon,
  Upload: Upload01Icon,
  User: UserIcon,
  Users: UsersIcon,
  Video: Video01Icon,
  Wallet: Wallet01Icon,
  Workflow: WorkflowIcon,
  Wrench: Wrench01Icon,
  X: XIcon,
  Zap: ZapIcon,
};

export function resolveHugeIcon(name: string | undefined | null): IconSvgElement {
  if (!name) return CircleIcon;
  return BY_LUCIDE_NAME[name] ?? CircleIcon;
}
